// Database types for The Chosen Generation
// These will be auto-generated by Supabase in production

export type UserRole = "admin" | "teacher" | "parent" | "child"

export type LevelType = "FS1" | "FS2" | "LEADERSHIP"

export type TaskType = "checkbox" | "short_answer" | "file_upload" | "teacher_approved"

export type SubmissionStatus = "pending" | "approved" | "rejected"

export type CheckinType = "prayer" | "attendance"

export type BadgeType =
  | "prayer_warrior"
  | "perfect_attendance"
  | "scripture_scholar"
  | "helping_hand"
  | "worship_leader"
  | "memory_master"
  | "faithful_student"
  | "early_bird"
  | "team_player"
  | "growth_champion"

export interface User {
  id: string
  email: string
  role: UserRole
  name: string
  phone?: string
  created_at: string
  updated_at: string
}

export interface Child {
  id: string
  parent_user_id: string
  display_name: string
  first_name: string
  last_name: string
  date_of_birth: string
  age_group: string
  gender: "male" | "female"
  class_id?: string
  current_level: LevelType
  pin_hash: string
  profile_photo_url?: string
  school_name?: string
  school_grade?: string
  medical_conditions?: string
  dietary_restrictions?: string
  special_needs?: string
  photo_consent: boolean
  enrollment_date: string
  created_at: string
  updated_at: string
}

export interface Class {
  id: string
  name: string
  age_group: string
  level: LevelType
  timezone?: string
  branch?: string
  teacher_user_id: string
  max_capacity: number
  current_enrollment: number
  schedule_day: string
  schedule_time: string
  created_at: string
  updated_at: string
}

export interface Task {
  id: string
  class_id: string
  week_start: string
  title: string
  description?: string
  type: TaskType
  requires_approval: boolean
  points: number
  due_date?: string
  order: number
  created_by_user_id: string
  created_at: string
  updated_at: string
}

export interface Submission {
  id: string
  task_id: string
  child_id: string
  status: SubmissionStatus
  content_text?: string
  file_url?: string
  feedback?: string
  approved_by_user_id?: string
  approved_at?: string
  created_at: string
  updated_at: string
}

export interface Checkin {
  id: string
  child_id: string
  type: CheckinType
  date: string
  value: boolean
  notes?: string
  verified_by_user_id?: string
  created_at: string
}

export interface Award {
  id: string
  child_id: string
  week_start: string
  badge_type: BadgeType
  title: string
  reason?: string
  given_by_user_id: string
  created_at: string
}

export interface Attendance {
  id: string
  child_id: string
  class_id: string
  session_date: string
  status: "present" | "absent" | "excused" | "late"
  check_in_time?: string
  check_out_time?: string
  notes?: string
  marked_by_user_id: string
  created_at: string
}

export interface PrayerHour {
  id: string
  child_id: string
  date: string
  duration_minutes: number
  type: "regular" | "extended_stretch" | "personal"
  engagement_rating?: number
  notes?: string
  recorded_by_user_id: string
  created_at: string
}

export interface ProgressAssessment {
  id: string
  child_id: string
  level: LevelType
  category: string
  score: number
  max_score: number
  notes?: string
  assessed_by_user_id: string
  assessment_date: string
  created_at: string
}

export interface Incident {
  id: string
  child_id: string
  incident_type: "behavioral_1" | "behavioral_2" | "behavioral_3" | "safeguarding" | "medical" | "accident"
  date: string
  time?: string
  location?: string
  description: string
  witnesses?: string
  immediate_action?: string
  reported_by_user_id: string
  escalated: boolean
  escalated_to_user_id?: string
  resolution?: string
  resolution_date?: string
  created_at: string
  updated_at: string
}

export interface AuditLog {
  id: string
  actor_user_id: string
  action: string
  entity_type: string
  entity_id: string
  details?: Record<string, unknown>
  ip_address?: string
  created_at: string
}

// UI-specific types
export interface WeeklyProgress {
  tasksCompleted: number
  totalTasks: number
  prayerDays: number
  attendanceRate: number
  badgesEarned: Award[]
}

export interface ChildDashboardData {
  child: Child
  class: Class | null
  weeklyProgress: WeeklyProgress
  currentTasks: Task[]
  submissions: Submission[]
  recentAwards: Award[]
}

export interface TeacherDashboardData {
  classes: Class[]
  childrenCount: number
  pendingSubmissions: number
  todayAttendance: Attendance[]
  weeklyReportsDue: number
}

export interface ParentDashboardData {
  children: Child[]
  upcomingSessions: { child: Child; class: Class; date: string }[]
  recentActivity: { type: string; child: Child; date: string; details: string }[]
}

// Badge configurations
export const BADGE_CONFIG: Record<BadgeType, { emoji: string; label: string; description: string }> = {
  prayer_warrior: {
    emoji: "🙏",
    label: "Prayer Warrior",
    description: "Completed 5 days of prayer check-ins",
  },
  perfect_attendance: {
    emoji: "⭐",
    label: "Perfect Attendance",
    description: "Attended all sessions this week",
  },
  scripture_scholar: {
    emoji: "📖",
    label: "Scripture Scholar",
    description: "Memorized all memory verses",
  },
  helping_hand: {
    emoji: "🤝",
    label: "Helping Hand",
    description: "Showed kindness and helped others",
  },
  worship_leader: {
    emoji: "🎵",
    label: "Worship Leader",
    description: "Participated actively in worship",
  },
  memory_master: {
    emoji: "🧠",
    label: "Memory Master",
    description: "Excellent memory verse recitation",
  },
  faithful_student: {
    emoji: "📚",
    label: "Faithful Student",
    description: "Completed all assignments",
  },
  early_bird: {
    emoji: "🌅",
    label: "Early Bird",
    description: "Always on time for sessions",
  },
  team_player: {
    emoji: "👥",
    label: "Team Player",
    description: "Great teamwork and cooperation",
  },
  growth_champion: {
    emoji: "🌱",
    label: "Growth Champion",
    description: "Showed significant spiritual growth",
  },
}

// Level configurations
export const LEVEL_CONFIG: Record<LevelType, { name: string; duration: string; passingScore: number; color: string }> = {
  FS1: {
    name: "Foundation School 1",
    duration: "2 weeks",
    passingScore: 60,
    color: "#22c55e", // green
  },
  FS2: {
    name: "Foundation School 2",
    duration: "3 weeks",
    passingScore: 70,
    color: "#3b82f6", // blue
  },
  LEADERSHIP: {
    name: "Leadership Training",
    duration: "2 weeks",
    passingScore: 80,
    color: "#a855f7", // purple
  },
}
